export const GETLANG="freelancer/registergetlang"
export const UPDATELANG="freelancer/updatelang"
export const SELECTLANG="freelancer/updatelang/select"
export const SELECTREAL="freelancer/updatelang/Real"
export const USERSELECT="freelancer/updatelang/UserSelect"
export const FTOKEN= "freelancer/updatelang/FTOsKEN"
export const PROGRESS = "freelancer/update/progress"
export const INTRO = "freelancer/updatelang/intro"
export const PROPOSAL = "freelancer/updatelang/proposal"

export const GETHTML = "freelancer/updatelang/gethtml"